[package]
name = "marcosdly/riptide-framework"
version = "0.8.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A lightweight and professional framework for Roblox."
license = "MIT"
authors = ["Riptide Development Group"]
exclude = ["docs/**", "test/**", "luau_packages/**", ".github/**"]
